### DISCUSSION TITLE
关于网站底部的中英文切换标识的隐藏

### DISCUSSION THREAD

**Discussion by smallkaka** [hugo-next/hugo-theme-next#172] [Q&A] [answered]
需求是：关闭网站底部的中英文切换标识
操作：在配置.ymal文件中注释了以下代码
``` 
languages:
  zh-cn:
    languageCode: zh-CN
    languageDirection: ltr
    languageName: "简体中文"
    weight: 1
  en-us:
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    weight: 2
    menus:
      main:
        - identifier: home
          name: Home
          pageRef: /
          pre: home
          weight: 1
        - identifier: about
          name: About
          pageRef: /about.html
          pre: user
          weight: 2
        - identifier: papers
          name: Papers
          pageRef: /post
          pre: book
          weight: 3
        - identifier: testCategory
          name: testCategory
          pageRef: /post/
          weight: 1
          parent: papers
        - identifier: archives
          name: Archives
          pageRef: /archives
          pre: archive
          weight: 4

    params:
      yearFormat: "2006"
      monthFormat: "01/02"
      dateFormat: "2006/01/02"
      timeFormat: "2006/01/02 15:04:05 -07:00"

      author: NexT Theme
      subtitle: Build for Hugo Theme
      description: Keep it simple, keep it powerful.
      keywords: Hugo,NexT,theme,simple,powerful

      linksSets:
        title: Links

      footer:
        beian:
          enable: false

      postFooter:
        endLineTip: "~ End Line ~"

      rewardSets:
        comment: '<i class="fa-solid fa-mug-hot"></i>  How about you buy me a coffee?ヾ(^▽^*)))'


```
出现问题：
```
2025-03-22 17:34:01.497 +0800
ERROR Failed to reload config: failed to create config from result: failed to decode "languages": no languages configured

```
