### DISCUSSION TITLE
数学公式突然不能识别了，另外能不能支持mermaid

### DISCUSSION THREAD

**Discussion by YuanLucas** [hugo-next/hugo-theme-next#25] [Q&A] [answered]
数学公式本来能正常显示的，后来不知怎的，所有数学公式都显示成代码了。检查过了math: true。

此外，能不能支持mermaid，用markdown简单画图呢。

**Comment by elkan1788** [comment, marked as answer]
不好意思，是因为近期在做优化，把一些暂时未实现的功能给隐藏了，你要着急的话，可以把主题目录下 `data/resourses.yaml` 文件里面的 `mathjax` 注释取消掉：
```
js:
  - name: animejs
    version: 3.2.1
    file: lib/anime.min.js
  # TODO
  #- name: mathjax
  #  version: 3.2.0
  #  file: es5/tex-mml-chtml.js
```

> 不过下次更新主题可能就要处理下冲突 😄 

关于 `mermaid` 是可以支持的，这个也是在功能计划之内，后面会实现的，敬请关注。
