### DISCUSSION TITLE
网站ICON图标修改失败，求教

### DISCUSSION THREAD

**Discussion by Emperor-Jude** [hugo-next/hugo-theme-next#38] [Q&A] [answered]
我在 public->imgs->icon 文件夹中将 Next 主题原带的网站 ico 文件删除，替换上我的 ico 图片，图标和原带的图标名一致。然后我使用 hugo 命令-> hugo server 命令。再在本地访问我的网站，发现网站图标还是原的 Next 图标。public->imgs->icon 文件夹中我的图标被 Next 图标覆盖。我应该怎么做，才可以将网站图标换成我的？
![image](https://user-images.githubusercontent.com/82216171/186612435-0a3c852e-9998-4588-a865-f4f4282a3adc.png)

**Comment by elkan1788** [comment, marked as answer]
不需要这么复杂，只需要在你的站点根目录下的 `static` 目录中创建个目录存放你的 icon 文件，比如 `imgs`，参考如下：

![static目录结构](https://user-images.githubusercontent.com/1217096/186634434-58cc678c-d305-4650-a5bc-e72cec469e8c.png)

然后在配置文件中找到 `favicon` 调整一下相应的路径即可，参考如下：
```yml
# 不同尺寸站点图标
# Different size of favicon
favicon:
  icon: /imgs/icons/favicon.ico
  small: /imgs/icons/favicon-16x16.png
  medium: /imgs/icons/favicon-32x32.png
  appleTouchIcon: /imgs/icons/apple-touch-icon.png
```

最后再重新运行 `hugo` 生成静态文件，或使用 `hugo server` 进行本地预览。
