### DISCUSSION TITLE
社交图标如何修改

### DISCUSSION THREAD

**Discussion by Justsenger** [hugo-next/hugo-theme-next#88] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/76653335/214457140-0bb0d261-6ce3-459d-99b9-7df17f7ad7f0.png)
这个社交图标怎么修改呢，想自定义

**Comment by elkan1788** [comment, marked as answer]
@Justsenger 直接在 https://fontawesome.com/ 上面找免费的ICON，搜索你喜欢的，然后拷贝名字，在 `config.yaml` 文件中找到 socials 配置项，添加修改对应的图标名称即可。

```
# 社交链接地址
# 用法： `Key: 名称 || 链接地址 || 图标`
# Key 用于排序建议从0开始
socials: 
  social0: Github || https://github.com/elkan1788 || fab fa-github
  social1: E-Mail || mailto:yourname@gmail.com || fa fa-envelope
  social2: 知乎 || https://www.zhihu.com/people/lisenhui || fa fa-book
```
