### ISSUE TITLE
分类页面无法正常显示小写英文字母开头的类别下文章数量

### ISSUE THREAD

**Issue by hxhue** [hugo-next/hugo-theme-next#136]
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。
(Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.)

## 问题自检列表 (Issue Checklist)

> 请确认如下情况已检查，并将 [ ] 换成 [x] 来选择 (Change [ ] to [x] to selected which your could make sure)

- [x] 已使用 Hugo Extended 0.86.0 或更高的版本 (I'm using Hugo Extended version 0.86.0 or later)
- [x] 已使用 Hugo NexT 4.0 或更高的版本 (I'm using Hugo NexT version 4.0 or later)
- [x] 已阅读 [Hugo 故障排除](https://gohugo.io/troubleshooting/)并尝试修复无果 (I had already read the [Troubleshooting page of Hugo](https://gohugo.io/troubleshooting/))
- [x] 已搜索过当前所有[已知问题](https://github.com/hugo-next/hugo-theme-next/issues)和[讨论区](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a) ，但没有找到帮助 (I had already searched for current [Issues](https://github.com/hugo-next/hugo-theme-next/issues) and [Q & A](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a), which does not help me.)

***

## 预期行为 (Expected behavior)

> 请描述你想实现的预期效果 (Please describe the expected behavior what you want)

分类数量是实际数量。

## 实际行为 (Actual behavior)

> 请同时提供网站链接、屏幕截图和源码地址 (Please provide your site links, screenshots and code repository)

分类数量为 0。

![image](https://github.com/hugo-next/hugo-theme-next/assets/48861499/21652714-47e3-471f-88a1-27ef764425fa)

## 问题重现步骤 (Steps to reproduce the behavior)

所有文章的 categories 都是小写，单词之间用连字符链接。比如：

```markdown
---
date: YYYY-MM-DD
categories:
  - some-category
---
```

可能问题：

https://github.com/hugo-next/hugo-theme-next/blob/8405b789e9857a040705f3beb9aad1fd21b61b89/layouts/_default/terms.html#L25-L31

在第 26 行首先获取了 category 的 title case，然后在第 30-31 行直接和文章的第一个 category 比较，所以会失败。将第 30-31 行改成这样就能正常获取类别下的文章数量（**实测能成功**）：

```html
            {{ range $pages }}
              {{ if eq (title (index .Params.categories 0)) $primaryCategory }}
```

### 主题配置(Configuration)

> 提供主题 `config.yaml` 中修改过的部分内容 (Paste ONLY CHANGED CONFIGURATION from  `config.yaml`)

<details>
<summary>config.yaml</summary>

```yaml
relativeLinks: true
uglyURLs: true
summaryLength: 140 #! 默认是 70
theme: hugo-theme-next
# 站点默认的语言和代码
defaultContentLanguage: zh-cn
languageCode: zh-CN

menus:
  main:
    - identifier: home
      name: 首页
      pageref: /
      pre: home
      weight: 1
    - identifier: about
      name: 关于
      pageref: /about.html
      pre: user
      weight: 2
    - identifier: archives
      name: 归档
      pageref: /archives.html
      pre: archive
      weight: 3
    - identifier: categories
      name: 分类
      pageref: /categories.html
      pre: th
      weight: 4
    - identifier: tags
      name: 标签
      pageref: /tags.html
      pre: tags
      weight: 5

  # 站点基本信息
  # Site Information Settings
  author: 😋
  subtitle: ""
  description: 个人博客
  keywords: ""
```

</details>

## 其他有用信息 (Other Information)

> 例如：操作系统、浏览器等 (e.g. Browser, System)

<details>
<summary>环境信息</summary>

```txt
版本	Windows 11 家庭中文版
版本	23H2
安装日期	‎2024/‎4/‎1
操作系统版本	22631.3374
体验	Windows Feature Experience Pack 1000.22688.1000.0

处理器	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
设备 ID	8AA07571-193D-49D8-9D50-9329677CFB6D
产品 ID	00342-35052-49627-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
```

</details>
