### ISSUE TITLE
如果文章标题有多个层级，建议在配置文件中自定义是否显示标题下方横线

### ISSUE THREAD

**Issue by zanxj** [hugo-next/hugo-theme-next#144]
请按照此新功能模版提供相关信息，如详细的功能描述或同类效果屏幕截图，这将有助于我们进行调查。
(Please follow this new feature template to provide relevant information, such as detail description for feature or some screenshots, which will help us investigate.)

## 新功能描述 (New feature description)

在当前最新版本（V4.6.2）主题，文章标题层级多的话，每行标题下方都会有一行下划线看上去很丑。可否在配置文件中自定义是否显示标题下划线？👇

![20240722202012](https://github.com/user-attachments/assets/347bfef6-1306-4af8-b8a8-187c46496263)

## 效果参考截图 (Screenshots if it possible)

在配置文件中自定义显示各级标题下划线👇

![20240722202210](https://github.com/user-attachments/assets/53591a89-317f-4ae9-a537-8fa9e249d9a2)

**Comment by elkan1788** [comment]
好的，后续看如何优化一下，也可以分享一下前面你通过自定义样式文件的操作方案。

**Comment by zanxj** [comment]
临时解决方案：
1.在配置文`config.yaml`件中开启自定义配置
```yaml
# 用户自定义文件配置
# Define custom file paths.
customFilePath:
#   sidebar: custom_sidebar.html
#   footer: custom_footer.html
  style: /css/custom_style.css
```

2.在`static/css/custom_style.css`添加以下内容（根据需要自定义）
```css
.post-body h1,.post-body h2 {
    border-bottom: 1px solid #eee
}
.post-body h3,.post-body h4 {
    border-bottom: 0px dotted #eee
}
```
