### ISSUE TITLE
animate.style设置失效

### ISSUE THREAD

**Issue by elkan1788** [hugo-next/hugo-theme-next#158]
### Discussed in https://github.com/hugo-next/hugo-theme-next/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **Laplace825** December 31, 2024</sup>
## 问题描述

在`config.yaml` 中设置的动画效果似乎不起作用，已经确认页面模式为 Gemini.

```yaml
  # 页面模式
  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

......

  # 通过 Animate.css 实现对整站的动画效果
  # Use Animate.css to animate everything.
  # For more information: https://animate.style
  motion:
    enable: true
    async: true
    transition:
      # All available transition variants: https://theme-next.js.org/animate/
      postBlock: zoomInLeft
      postHeader: bounceIn
      postBody: zoomIn
      collHeader: zoomInLeft
      # 侧边样效果 只有在 Pisces | Gemini 模式下才支持
      # Only for Pisces | Gemini.
      sidebar: zoomInLeft
```

## 操作过程

```bash
hugo new site next_test
cd next_test
git init
git submodule add -b develop https://github.com/hugo-next/hugo-theme-next.git themes/hugo-theme-next
cp ./themes/hugo-theme-next/exampleSite/config.yaml .
cp -r ./themes/hugo-theme-next/assets .
cp -r ./themes/hugo-theme-next/data/ .
cp -r ./themes/hugo-theme-next/layouts .
cp -r ./themes/hugo-theme-next/static .
cp -r ./themes/hugo-theme-next/i18n .
cp -r ./themes/hugo-theme-next/images .
git submodule update
nvim . # 这里修改 config.yaml 中的 animation
cp -r ./themes/hugo-theme-next/exampleSite/content/ ./
hugo server -D -E -F
```</div>
