### ISSUE TITLE
waline pageview不可加载

### ISSUE THREAD

**Issue by finisky** [hugo-next/hugo-theme-next#41]
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。
(Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.)

## 问题自检列表 (Issue Checklist)

> 请确认如下情况已检查，并将 [ ] 换成 [x] 来选择 (Change [ ] to [x] to selected which your could make sure)

- [x] 已使用 Hugo Extended 0.86.0 或更高的版本 (I'm using Hugo Extended version 0.86.0 or later)
- [x] 已使用 Hugo NexT 4.0 或更高的版本 (I'm using Hugo NexT version 4.0 or later)
- [x] 已阅读 [Hugo 故障排除](https://gohugo.io/troubleshooting/)并尝试修复无果 (I had already read the [Troubleshooting page of Hugo](https://gohugo.io/troubleshooting/))
- [x] 已搜索过当前所有[已知问题](https://github.com/hugo-next/hugo-theme-next/issues)和[讨论区](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a) ，但没有找到帮助 (I had already searched for current [Issues](https://github.com/hugo-next/hugo-theme-next/issues) and [Q & A](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a), which does not help me.)

***

## 预期行为 (Expected behavior)

> 请描述你想实现的预期效果 (Please describe the expected behavior what you want)
正确加载pageview count

## 实际行为 (Actual behavior)

> 请同时提供网站链接、屏幕截图和源码地址 (Please provide your site links, screenshots and code repository)
![image](https://user-images.githubusercontent.com/50729876/186716037-d9e944cb-ba8e-4041-8d78-6ba16f978499.png)

## 问题重现步骤 (Steps to reproduce the behavior)
waline开启pageview，views不可加载，直到滑动页面到底部，waline comment加载成功之后view count才可加载成功。应该是waline懒加载导致的问题，可能的解决方案是单独加载waline pageview js

### 主题配置(Configuration)

> 提供主题 `config.yaml` 中修改过的部分内容 (Paste ONLY CHANGED CONFIGURATION from  `config.yaml`)

```yaml
 waline:
    serverURL: https://xxx.vercel.app
    cssUrl: https://unpkg.com/@waline/client@v2/dist/waline.css
    pageSize: 10 # Pagination size
    lang: en-US
    commentCount: true
    pageView: true
    wordLimit: 200
    requiredMeta: ['nick', 'mail']
```

## 其他有用信息 (Other Information)

> 例如：操作系统、浏览器等 (e.g. Browser, System)
